@startuml
'title Standard modelling metamodel

!startsub STYLE
class test
!endsub

'scale 1000 width
'skinparam packageStyle frame
'skinparam linetype polyline
'top to bottom direction
hide empty members
'hide circle
'hide stereotype 

' spare colours from the palette... #FE88B1,#C9DB74,#8BE0A4,#B497E7,#D3B484,#B3B3B3

class term as "Term" << (T,#66C5CC) >> {
{field} Definition
}
class concept as "Concept"<< (C,#F6CF71) >> {
{field} Definition
}
class reference as "Reference" << (R,#F89C74) >> {
{field} Description
}
class deliverable as "Deliverable" << (D,#DCB0F2) >> {
{field} Description
Necessity : Mandatory/Recommended/Optional
}
class activity as "Activity" << (A,#87C55F) >> {
{field} Description
Necessity : Mandatory/Recommended/Optional
}
class party as "Party" << (P,#9EB9F3) >> {
{field} Description
Necessity : Mandatory/Recommended/Optional
}

term - concept : used in >
activity -- activity : used in >
party -- party : part of >
activity -- deliverable : produces >
party -- activity : carries out >
activity -- reference : detailed in >
concept -- reference : detailed in >
@enduml
