@startuml
title Standard modelling metamodel
'scale 1000 width
'skinparam packageStyle frame
'skinparam linetype polyline
'top to bottom direction
hide members
'hide circle
'hide stereotype 

class term as "Term"
class concept as "Concept"
class reference as "Reference"
class deliverable as "Deliverable"

term - concept : used in >
@enduml
